version: '3'
services:
    discovery:
        build: ShortURLDiscoveryService
        environment: 
            - "eureka.client.serviceUrl.defaultZone=http://discovery:8010/eureka/"
        ports:
            - "8010:8010"
    zuul:
        build: ZuulGateway
        environment: 
            - "eureka.client.serviceUrl.defaultZone=http://discovery:8010/eureka/"
        ports:
            - "8011:8011"
        depends_on:
            - discovery
    postgresql:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
            POSTGRES_DB: test
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
    users:
        build: UsersMS
        environment:
            - "eureka.client.serviceUrl.defaultZone=http://discovery:8010/eureka/"
            - "spring.datasource.url=jdbc:postgresql://postgresql:5432/test"
        depends_on:
            - discovery
            - postgresql
#Added for PostgreSQL as the only known fix for Windows
volumes:
    pgdata: